# This file was generated by @liquid-labs/sdlc-projects-workflow-local-node-build.
# Refer to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-local-
# node-build for further details

#####
# build dist/index.js
#####

SDLC_INDEX_JS:=$(DIST)/index.js
SDLC_INDEX_JS_ENTRY=$(SRC)/index.js
BUILD_TARGETS+=$(SDLC_INDEX_JS)

$(SDLC_INDEX_JS): package.json $(SDLC_ALL_NON_TEST_JS_FILES_SRC) $(SRC)/file-header.txt
	JS_BUILD_TARGET=$(SDLC_INDEX_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(SDLC_ROLLUP) --config $(SDLC_ROLLUP_CONFIG)

#####
# end dist/index.js
#####
